field: 85898001-9c9c-4d46-abf9-a928e44f0d48 # Body Content
fieldLayouts:
  73ac25bc-ace9-4aa6-ba1d-9211b5c06027:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 735b5e6e-8026-4de4-8e32-14e03d975565 # Image
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c9b2074e-9c0c-42ca-912b-da62df8b651a
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: fd670a04-b06c-4830-b8d0-5e2d388ce9a1 # Caption
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3a0ff308-aab3-40f3-9e76-e651b423ca1c
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 503ce48e-30a9-4ab1-9dd4-89fec70a385c # Style
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d2dbe0c8-d8a4-48cc-b4ba-082ee622ac0b
            userCondition: null
            warning: null
            width: 25
        name: Content
        uid: c7f52bda-4083-406b-982c-63def615500a
        userCondition: null
fields:
  503ce48e-30a9-4ab1-9dd4-89fec70a385c: # Style
    columnSuffix: vaeqrzhy
    contentColumnType: string
    fieldGroup: null
    handle: style
    instructions: null
    name: Style
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - 'Wide (XL screens only)'
            -
              - value
              - wide
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Checkboxes
  735b5e6e-8026-4de4-8e32-14e03d975565: # Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: null
    name: Image
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - image
      branchLimit: null
      defaultUploadLocationSource: 'volume:5a0be839-14a2-465e-a504-bb63dd0281e9' # Images
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 1
      minRelations: null
      previewMode: thumbs
      restrictFiles: true
      restrictLocation: true
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:5a0be839-14a2-465e-a504-bb63dd0281e9' # Images
      restrictedLocationSubpath: 'entry/{owner.canonicalId}'
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
          -
            - conditionRules
            -
              -
                __assoc__:
                  -
                    - class
                    - craft\elements\conditions\assets\WidthConditionRule
                  -
                    - uid
                    - c2f227f4-49cc-4b5a-ab14-43a864cbfaea
                  -
                    - operator
                    - '>='
                  -
                    - value
                    - '800'
                  -
                    - maxValue
                    - ''
      selectionLabel: null
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      sources:
        - 'volume:5a0be839-14a2-465e-a504-bb63dd0281e9' # Images
      targetSiteId: null
      validateRelatedElements: true
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  fd670a04-b06c-4830-b8d0-5e2d388ce9a1: # Caption
    columnSuffix: ezpjampo
    contentColumnType: string(240)
    fieldGroup: null
    handle: caption
    instructions: null
    name: Caption
    searchable: true
    settings:
      byteLimit: null
      charLimit: 60
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: language
    type: craft\fields\PlainText
handle: image
name: Image
sortOrder: 3
