field: 85898001-9c9c-4d46-abf9-a928e44f0d48 # Body Content
fieldLayouts:
  208f5868-6f1a-4491-b819-458390ab267c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: ba328fdf-594b-42f5-b083-3b55765dd8ef # Heading
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5605656f-e22e-4696-bca0-9d756bd6eb70
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: cee9ebb3-ce52-4a35-9a98-0ff3c43853a7 # Text
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bb94c828-0ca3-4926-a7ce-c8ba3085f138
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6e507a59-e39c-49c8-9d8b-2066317bda3f # Location
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b76e2156-27cf-4c02-8556-83d035c86e3e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 164e611f-6177-4d07-a94e-8aaf8395299c # Date and Time
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1eba02c7-3ca9-4e5e-a0f8-53a781379216
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a82ceefa-7dad-42b6-bb96-63b0f115ffdf # External Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d433292f-8470-42e4-98a1-eeace1ef06b0
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 683a12c1-5bbb-47b1-b292-105fd3aaa89e
        userCondition: null
fields:
  6e507a59-e39c-49c8-9d8b-2066317bda3f: # Location
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: location
    instructions: null
    name: Location
    searchable: false
    settings:
      allowSelfRelations: false
      branchLimit: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 1
      minRelations: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Entry
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\entries\EntryCondition
      selectionLabel: null
      showSiteMenu: false
      sources:
        - 'section:fde6b0e6-02b7-426c-9600-7c39eaf0a485' # Location
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  164e611f-6177-4d07-a94e-8aaf8395299c: # Date and Time
    columnSuffix: drclogkp
    contentColumnType: text
    fieldGroup: null
    handle: dateAndTime
    instructions: null
    name: 'Date and Time'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 2
      multiline: true
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: language
    type: craft\fields\PlainText
  a82ceefa-7dad-42b6-bb96-63b0f115ffdf: # External Link
    columnSuffix: uypoopcs
    contentColumnType: string(255)
    fieldGroup: null
    handle: externalLink
    instructions: null
    name: 'External Link'
    searchable: false
    settings:
      maxLength: 255
      types:
        - url
    translationKeyFormat: null
    translationMethod: language
    type: craft\fields\Url
  ba328fdf-594b-42f5-b083-3b55765dd8ef: # Heading
    columnSuffix: bpzztumm
    contentColumnType: string(250)
    fieldGroup: null
    handle: heading
    instructions: null
    name: Heading
    searchable: true
    settings:
      byteLimit: 250
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: language
    type: craft\fields\PlainText
  cee9ebb3-ce52-4a35-9a98-0ff3c43853a7: # Text
    columnSuffix: mexnfybm
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: null
    name: Text
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: true
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: language
    type: craft\fields\PlainText
handle: listItem
name: 'List Item'
sortOrder: 5
