field: 85898001-9c9c-4d46-abf9-a928e44f0d48 # Body Content
fieldLayouts:
  9993e1fd-6b85-41a5-b5a3-efe51568597e:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: be7b43ab-37cd-4a4c-be64-68f6a0a15eb0 # Text
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3c11856d-7122-4296-b607-943240ccc31e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e7c37b4a-837a-4b30-b183-c2c8d82f92d7 # Attribution
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d64e2481-fc99-4ef5-9e2b-f2153f5d9d20
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 98dc8cd6-5222-4641-8b73-1843c5892502
        userCondition: null
fields:
  be7b43ab-37cd-4a4c-be64-68f6a0a15eb0: # Text
    columnSuffix: zuqosjkm
    contentColumnType: string
    fieldGroup: null
    handle: text
    instructions: null
    name: Text
    searchable: true
    settings:
      byteLimit: 250
      charLimit: null
      code: false
      columnType: string
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: language
    type: craft\fields\PlainText
  e7c37b4a-837a-4b30-b183-c2c8d82f92d7: # Attribution
    columnSuffix: nwfddwxj
    contentColumnType: string(240)
    fieldGroup: null
    handle: attribution
    instructions: null
    name: Attribution
    searchable: false
    settings:
      byteLimit: null
      charLimit: 60
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: language
    type: craft\fields\PlainText
handle: quote
name: Quote
sortOrder: 4
