columnSuffix: svvaemtm
contentColumnType: boolean
fieldGroup: bd76fb6e-8765-41d3-8e8a-02e37e127c80 # Common
handle: featured
instructions: null
name: Featured
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
